<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CategorySeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		$entries = [
			[
				'translation_lang' => 'en',
				'translation_of'   => '1',
				'parent_id'        => null,
				'name'             => 'Automobiles',
				'slug'             => 'automobiles',
				'description'      => null,
				'picture'          => 'app/categories/skin-blue/car.png',
				'icon_class'       => 'fa fa-car',
				'lft'              => '0',
				'rgt'              => '0',
				'depth'            => '0',
				'type'             => 'classified',
				'is_for_permanent' => '0',
				'active'           => '1',
				'children'         => [
					[
						'translation_lang' => 'en',
						'translation_of'   => '2',
						'parent_id'        => null,
						'name'             => 'Cars',
						'slug'             => 'cars',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '3',
						'parent_id'        => null,
						'name'             => 'Buses & Minibus',
						'slug'             => 'buses-and-minibus',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '4',
						'parent_id'        => null,
						'name'             => 'Heavy Equipment',
						'slug'             => 'heavy-equipment',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '5',
						'parent_id'        => null,
						'name'             => 'Motorcycles & Scooters',
						'slug'             => 'motorcycles-and-scooters',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '6',
						'parent_id'        => null,
						'name'             => 'Trucks & Trailers',
						'slug'             => 'trucks-and-trailers',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '7',
						'parent_id'        => null,
						'name'             => 'Vehicle Parts & Accessories',
						'slug'             => 'car-parts-and-accessories',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '8',
						'parent_id'        => null,
						'name'             => 'Watercraft & Boats',
						'slug'             => 'watercraft-and-boats',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
				],
			],
			[
				'translation_lang' => 'en',
				'translation_of'   => '9',
				'parent_id'        => null,
				'name'             => 'Phones & Tablets',
				'slug'             => 'phones-and-tablets',
				'description'      => null,
				'picture'          => 'app/categories/skin-blue/mobile-alt.png',
				'icon_class'       => 'icon-laptop',
				'lft'              => '0',
				'rgt'              => '0',
				'depth'            => '0',
				'type'             => 'classified',
				'is_for_permanent' => '0',
				'active'           => '1',
				'children'         => [
					[
						'translation_lang' => 'en',
						'translation_of'   => '10',
						'parent_id'        => null,
						'name'             => 'Mobile Phones',
						'slug'             => 'mobile-phones',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '11',
						'parent_id'        => null,
						'name'             => 'Accessories for Mobile Phones & Tablets',
						'slug'             => 'mobile-phones-tablets-accessories',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '12',
						'parent_id'        => null,
						'name'             => 'Smart Watches & Trackers',
						'slug'             => 'smart-watches-and-trackers',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '13',
						'parent_id'        => null,
						'name'             => 'Tablets',
						'slug'             => 'tablets',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
				],
			],
			[
				'translation_lang' => 'en',
				'translation_of'   => '14',
				'parent_id'        => null,
				'name'             => 'Electronics',
				'slug'             => 'electronics',
				'description'      => null,
				'picture'          => 'app/categories/skin-blue/fa-laptop.png',
				'icon_class'       => 'icon-theatre',
				'lft'              => '0',
				'rgt'              => '0',
				'depth'            => '0',
				'type'             => 'classified',
				'is_for_permanent' => '0',
				'active'           => '1',
				'children'         => [
					[
						'translation_lang' => 'en',
						'translation_of'   => '15',
						'parent_id'        => null,
						'name'             => 'Accessories & Supplies for Electronics',
						'slug'             => 'accessories-supplies for Electronics',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '16',
						'parent_id'        => null,
						'name'             => 'Laptops & Computers',
						'slug'             => 'laptops-and-computers',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '17',
						'parent_id'        => null,
						'name'             => 'TV & DVD Equipment',
						'slug'             => 'tv-dvd-equipment',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '18',
						'parent_id'        => null,
						'name'             => 'Audio & Music Equipment',
						'slug'             => 'audio-music-equipment',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '19',
						'parent_id'        => null,
						'name'             => 'Computer Accessories',
						'slug'             => 'computer-accessories',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '20',
						'parent_id'        => null,
						'name'             => 'Computer Hardware',
						'slug'             => 'computer-hardware',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '21',
						'parent_id'        => null,
						'name'             => 'Computer Monitors',
						'slug'             => 'computer-monitors',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '22',
						'parent_id'        => null,
						'name'             => 'Headphones',
						'slug'             => 'headphones',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '23',
						'parent_id'        => null,
						'name'             => 'Networking Products',
						'slug'             => 'networking-products',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '24',
						'parent_id'        => null,
						'name'             => 'Photo & Video Cameras',
						'slug'             => 'photo-video-cameras',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '25',
						'parent_id'        => null,
						'name'             => 'Printers & Scanners',
						'slug'             => 'printers-and-scanners',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '26',
						'parent_id'        => null,
						'name'             => 'Security & Surveillance',
						'slug'             => 'security-and-surveillance',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '27',
						'parent_id'        => null,
						'name'             => 'Software',
						'slug'             => 'software',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '28',
						'parent_id'        => null,
						'name'             => 'Video Games',
						'slug'             => 'video-games',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '29',
						'parent_id'        => null,
						'name'             => 'Game Consoles',
						'slug'             => 'video-game-consoles',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
				],
			],
			[
				'translation_lang' => 'en',
				'translation_of'   => '30',
				'parent_id'        => null,
				'name'             => 'Furniture & Appliances',
				'slug'             => 'furniture-appliances',
				'description'      => null,
				'picture'          => 'app/categories/skin-blue/couch.png',
				'icon_class'       => 'icon-basket-1',
				'lft'              => '0',
				'rgt'              => '0',
				'depth'            => '0',
				'type'             => 'classified',
				'is_for_permanent' => '0',
				'active'           => '1',
				'children'         => [
					[
						'translation_lang' => 'en',
						'translation_of'   => '31',
						'parent_id'        => null,
						'name'             => 'Furniture - Tableware',
						'slug'             => 'furniture-tableware',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '32',
						'parent_id'        => null,
						'name'             => 'Antiques - Art - Decoration',
						'slug'             => 'antiques-art-decoration',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '33',
						'parent_id'        => null,
						'name'             => 'Appliances',
						'slug'             => 'appliances',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '34',
						'parent_id'        => null,
						'name'             => 'Garden',
						'slug'             => 'garden',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '35',
						'parent_id'        => null,
						'name'             => 'Toys - Games - Figurines',
						'slug'             => 'toys-games-figurines',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '36',
						'parent_id'        => null,
						'name'             => 'Wine & Gourmet - Recipes',
						'slug'             => 'wine-gourmet-recipes',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
				],
			],
			[
				'translation_lang' => 'en',
				'translation_of'   => '37',
				'parent_id'        => null,
				'name'             => 'Real estate',
				'slug'             => 'real-estate',
				'description'      => null,
				'picture'          => 'app/categories/skin-blue/fa-home.png',
				'icon_class'       => 'icon-home',
				'lft'              => '0',
				'rgt'              => '0',
				'depth'            => '0',
				'type'             => 'classified',
				'is_for_permanent' => '0',
				'active'           => '1',
				'children'         => [
					[
						'translation_lang' => 'en',
						'translation_of'   => '38',
						'parent_id'        => null,
						'name'             => 'Houses & Apartments For Rent',
						'slug'             => 'houses-apartments-for-rent',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '39',
						'parent_id'        => null,
						'name'             => 'Houses & Apartments For Sale',
						'slug'             => 'houses-apartments-for-sale',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '40',
						'parent_id'        => null,
						'name'             => 'Land & Plots for Rent',
						'slug'             => 'land-and-plots-for-rent',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '41',
						'parent_id'        => null,
						'name'             => 'Land & Plots For Sale',
						'slug'             => 'land-and-plots-for-sale',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '42',
						'parent_id'        => null,
						'name'             => 'Commercial Property For Rent',
						'slug'             => 'commercial-property-for-rent',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '43',
						'parent_id'        => null,
						'name'             => 'Commercial Property For Sale',
						'slug'             => 'commercial-properties',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '44',
						'parent_id'        => null,
						'name'             => 'Event centres, Venues and Workstations',
						'slug'             => 'event-centers-and-venues',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '45',
						'parent_id'        => null,
						'name'             => 'Short Rental',
						'slug'             => 'temporary-and-vacation-rentals',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
				],
			],
			[
				'translation_lang' => 'en',
				'translation_of'   => '46',
				'parent_id'        => null,
				'name'             => 'Animals & Pets',
				'slug'             => 'animals-and-pets',
				'description'      => null,
				'picture'          => 'app/categories/skin-blue/paw.png',
				'icon_class'       => 'icon-guidedog',
				'lft'              => '0',
				'rgt'              => '0',
				'depth'            => '0',
				'type'             => 'classified',
				'is_for_permanent' => '0',
				'active'           => '1',
				'children'         => [
					[
						'translation_lang' => 'en',
						'translation_of'   => '47',
						'parent_id'        => null,
						'name'             => 'Birds',
						'slug'             => 'birds',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '48',
						'parent_id'        => null,
						'name'             => 'Cats & Kittens',
						'slug'             => 'cats-and-kittens',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '49',
						'parent_id'        => null,
						'name'             => 'Dogs',
						'slug'             => 'dogs-and-puppies',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '50',
						'parent_id'        => null,
						'name'             => 'Fish',
						'slug'             => 'fish',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '51',
						'parent_id'        => null,
						'name'             => 'Pet\'s Accessories',
						'slug'             => 'pets-accessories',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '52',
						'parent_id'        => null,
						'name'             => 'Reptiles',
						'slug'             => 'reptiles',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '53',
						'parent_id'        => null,
						'name'             => 'Other Animals',
						'slug'             => 'other-animals',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
				],
			],
			[
				'translation_lang' => 'en',
				'translation_of'   => '54',
				'parent_id'        => null,
				'name'             => 'Fashion',
				'slug'             => 'fashion',
				'description'      => null,
				'picture'          => 'app/categories/skin-blue/tshirt.png',
				'icon_class'       => 'icon-heart',
				'lft'              => '0',
				'rgt'              => '0',
				'depth'            => '0',
				'type'             => 'classified',
				'is_for_permanent' => '0',
				'active'           => '1',
				'children'         => [
					[
						'translation_lang' => 'en',
						'translation_of'   => '55',
						'parent_id'        => null,
						'name'             => 'Bags',
						'slug'             => 'bags',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '56',
						'parent_id'        => null,
						'name'             => 'Clothing',
						'slug'             => 'clothing',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '57',
						'parent_id'        => null,
						'name'             => 'Clothing Accessories',
						'slug'             => 'clothing-accessories',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '58',
						'parent_id'        => null,
						'name'             => 'Jewelry',
						'slug'             => 'jewelry',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '59',
						'parent_id'        => null,
						'name'             => 'Shoes',
						'slug'             => 'shoes',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '60',
						'parent_id'        => null,
						'name'             => 'Watches',
						'slug'             => 'watches',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '61',
						'parent_id'        => null,
						'name'             => 'Wedding Wear & Accessories',
						'slug'             => 'wedding-wear-accessories',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
				],
			],
			[
				'translation_lang' => 'en',
				'translation_of'   => '62',
				'parent_id'        => null,
				'name'             => 'Beauty & Well being',
				'slug'             => 'beauty-well-being',
				'description'      => null,
				'picture'          => 'app/categories/skin-blue/spa.png',
				'icon_class'       => 'icon-search',
				'lft'              => '0',
				'rgt'              => '0',
				'depth'            => '0',
				'type'             => 'classified',
				'is_for_permanent' => '0',
				'active'           => '1',
				'children'         => [
					[
						'translation_lang' => 'en',
						'translation_of'   => '63',
						'parent_id'        => null,
						'name'             => 'Bath & Body',
						'slug'             => 'bath-and-body',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '64',
						'parent_id'        => null,
						'name'             => 'Fragrance',
						'slug'             => 'fragrance',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '65',
						'parent_id'        => null,
						'name'             => 'Hair Beauty',
						'slug'             => 'hair-beauty',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '66',
						'parent_id'        => null,
						'name'             => 'Makeup',
						'slug'             => 'makeup',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '67',
						'parent_id'        => null,
						'name'             => 'Sexual Wellness',
						'slug'             => 'sexual-wellness',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '68',
						'parent_id'        => null,
						'name'             => 'Skin Care',
						'slug'             => 'skin-care',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '69',
						'parent_id'        => null,
						'name'             => 'Tobacco Accessories',
						'slug'             => 'tobacco-accessories',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '70',
						'parent_id'        => null,
						'name'             => 'Tools & Accessories',
						'slug'             => 'tools-and-accessories',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '71',
						'parent_id'        => null,
						'name'             => 'Vitamins & Supplements',
						'slug'             => 'vitamins-and-supplements',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '72',
						'parent_id'        => null,
						'name'             => 'Pro Massage',
						'slug'             => 'pro-massage',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
				],
			],
			[
				'translation_lang' => 'en',
				'translation_of'   => '73',
				'parent_id'        => null,
				'name'             => 'Jobs',
				'slug'             => 'jobs',
				'description'      => null,
				'picture'          => 'app/categories/skin-blue/mfglabs-users.png',
				'icon_class'       => 'icon-megaphone-1',
				'lft'              => '0',
				'rgt'              => '0',
				'depth'            => '0',
				'type'             => 'job-offer',
				'is_for_permanent' => '0',
				'active'           => '1',
				'children'         => [
					[
						'translation_lang' => 'en',
						'translation_of'   => '74',
						'parent_id'        => null,
						'name'             => 'Agriculture - Environment',
						'slug'             => 'agriculture-environment',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'job-offer',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '75',
						'parent_id'        => null,
						'name'             => 'Assistantship - Secretariat - Helpdesk',
						'slug'             => 'assistantship-secretariat-helpdesk',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'job-offer',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '76',
						'parent_id'        => null,
						'name'             => 'Automotive - Mechanic',
						'slug'             => 'automotive-mechanic',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'job-offer',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '77',
						'parent_id'        => null,
						'name'             => 'BTP - Construction - Building',
						'slug'             => 'btp-construction-building',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'job-offer',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '78',
						'parent_id'        => null,
						'name'             => 'Trade - Business Services',
						'slug'             => 'trade-business-services',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'job-offer',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '79',
						'parent_id'        => null,
						'name'             => 'Commercial - Sale Jobs',
						'slug'             => 'commercial-sale-jobs',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'job-offer',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '80',
						'parent_id'        => null,
						'name'             => 'Accounting - Management - Finance',
						'slug'             => 'accounting-management-finance',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'job-offer',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '81',
						'parent_id'        => null,
						'name'             => 'Steering - Manager',
						'slug'             => 'steering-manager',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'job-offer',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '82',
						'parent_id'        => null,
						'name'             => 'Aesthetics - Hair - Beauty',
						'slug'             => 'aesthetics-hair-beauty',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'job-offer',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '83',
						'parent_id'        => null,
						'name'             => 'Public Service Jobs',
						'slug'             => 'public-service-jobs',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'job-offer',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '84',
						'parent_id'        => null,
						'name'             => 'Real Estate Jobs',
						'slug'             => 'real-estate-jobs',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'job-offer',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '85',
						'parent_id'        => null,
						'name'             => 'Independent - Freelance - Telecommuting',
						'slug'             => 'independent-freelance-telecommuting',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'job-offer',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '86',
						'parent_id'        => null,
						'name'             => 'Computers - Internet - Telecommunications',
						'slug'             => 'computers-internet-telecommunications',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'job-offer',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '87',
						'parent_id'        => null,
						'name'             => 'Industry, Production & engineering',
						'slug'             => 'industry-production-engineering',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'job-offer',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '88',
						'parent_id'        => null,
						'name'             => 'Marketing - Communication',
						'slug'             => 'marketing-communication',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'job-offer',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '89',
						'parent_id'        => null,
						'name'             => 'Babysitting - Nanny Work',
						'slug'             => 'babysitting-nanny-work',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'job-offer',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '90',
						'parent_id'        => null,
						'name'             => 'HR - Training - Education',
						'slug'             => 'hr-training-education',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'job-offer',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '91',
						'parent_id'        => null,
						'name'             => 'Medical - Healthcare - Social',
						'slug'             => 'medical-healthcare-social',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'job-offer',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '92',
						'parent_id'        => null,
						'name'             => 'Security - Guarding',
						'slug'             => 'security-guarding',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'job-offer',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '93',
						'parent_id'        => null,
						'name'             => 'Household Services - Housekeeping',
						'slug'             => 'household-services-housekeeping',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'job-offer',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '94',
						'parent_id'        => null,
						'name'             => 'Tourism - Hotels - Restaurants - Leisure',
						'slug'             => 'tourism-hotels-restaurants-leisure',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'job-offer',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '95',
						'parent_id'        => null,
						'name'             => 'Transportation - Logistics',
						'slug'             => 'transportation-logistics',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'job-offer',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '96',
						'parent_id'        => null,
						'name'             => 'Others Jobs Offer',
						'slug'             => 'others-jobs-offer',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'job-offer',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
				],
			],
			[
				'translation_lang' => 'en',
				'translation_of'   => '97',
				'parent_id'        => null,
				'name'             => 'Services',
				'slug'             => 'services',
				'description'      => null,
				'picture'          => 'app/categories/skin-blue/ion-clipboard.png',
				'icon_class'       => 'fa fa-briefcase',
				'lft'              => '0',
				'rgt'              => '0',
				'depth'            => '0',
				'type'             => 'classified',
				'is_for_permanent' => '0',
				'active'           => '1',
				'children'         => [
					[
						'translation_lang' => 'en',
						'translation_of'   => '98',
						'parent_id'        => null,
						'name'             => 'Casting, Model, Photographer',
						'slug'             => 'casting-model-photographer',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '99',
						'parent_id'        => null,
						'name'             => 'Carpooling',
						'slug'             => 'carpooling',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '100',
						'parent_id'        => null,
						'name'             => 'Moving, Furniture Guard',
						'slug'             => 'moving-furniture-guard',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '101',
						'parent_id'        => null,
						'name'             => 'Destocking - Commercial',
						'slug'             => 'destocking-commercial',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '102',
						'parent_id'        => null,
						'name'             => 'Industrial Equipment',
						'slug'             => 'industrial-equipment',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '103',
						'parent_id'        => null,
						'name'             => 'Aesthetics, Hairstyling',
						'slug'             => 'aesthetics-hairstyling',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '104',
						'parent_id'        => null,
						'name'             => 'Materials and Equipment Pro',
						'slug'             => 'materials-and-equipment-pro',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '105',
						'parent_id'        => null,
						'name'             => 'Event Organization Services',
						'slug'             => 'event-organization-services',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '106',
						'parent_id'        => null,
						'name'             => 'Service Provision',
						'slug'             => 'service-provision',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '107',
						'parent_id'        => null,
						'name'             => 'Health, Beauty',
						'slug'             => 'health-beauty',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '108',
						'parent_id'        => null,
						'name'             => 'Artisan, Troubleshooting, Handyman',
						'slug'             => 'artisan-troubleshooting-handyman',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '109',
						'parent_id'        => null,
						'name'             => 'Computing Services',
						'slug'             => 'computing-services',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '110',
						'parent_id'        => null,
						'name'             => 'Tourism and Travel Services',
						'slug'             => 'tourism-and-travel-services',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '111',
						'parent_id'        => null,
						'name'             => 'Translation, Writing',
						'slug'             => 'translation-writing',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '112',
						'parent_id'        => null,
						'name'             => 'Construction - Renovation - Carpentry',
						'slug'             => 'construction-renovation-carpentry',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '113',
						'parent_id'        => null,
						'name'             => 'Other services',
						'slug'             => 'other-services',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
				],
			],
			[
				'translation_lang' => 'en',
				'translation_of'   => '114',
				'parent_id'        => null,
				'name'             => 'Learning',
				'slug'             => 'learning',
				'description'      => null,
				'picture'          => 'app/categories/skin-blue/fa-graduation-cap.png',
				'icon_class'       => 'icon-book-open',
				'lft'              => '0',
				'rgt'              => '0',
				'depth'            => '0',
				'type'             => 'classified',
				'is_for_permanent' => '0',
				'active'           => '1',
				'children'         => [
					[
						'translation_lang' => 'en',
						'translation_of'   => '115',
						'parent_id'        => null,
						'name'             => 'Language Classes',
						'slug'             => 'language-classes',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '116',
						'parent_id'        => null,
						'name'             => 'Computer Courses',
						'slug'             => 'computer-courses',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '117',
						'parent_id'        => null,
						'name'             => 'Tutoring, Private Lessons',
						'slug'             => 'tutoring-private-lessons',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '118',
						'parent_id'        => null,
						'name'             => 'Vocational Training',
						'slug'             => 'vocational-training',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '119',
						'parent_id'        => null,
						'name'             => 'Maths, Physics, Chemistry',
						'slug'             => 'maths-physics-chemistry',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '120',
						'parent_id'        => null,
						'name'             => 'Music, Theatre, Dance',
						'slug'             => 'music-theatre-dance',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '121',
						'parent_id'        => null,
						'name'             => 'School support',
						'slug'             => 'school-support',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
				],
			],
			[
				'translation_lang' => 'en',
				'translation_of'   => '122',
				'parent_id'        => null,
				'name'             => 'Local Events',
				'slug'             => 'local-events',
				'description'      => null,
				'picture'          => 'app/categories/skin-blue/calendar-alt.png',
				'icon_class'       => 'icon-megaphone-1',
				'lft'              => '0',
				'rgt'              => '0',
				'depth'            => '0',
				'type'             => 'classified',
				'is_for_permanent' => '0',
				'active'           => '1',
				'children'         => [
					[
						'translation_lang' => 'en',
						'translation_of'   => '123',
						'parent_id'        => null,
						'name'             => 'Concerts & Festivals',
						'slug'             => 'concerts-and-festivals',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '124',
						'parent_id'        => null,
						'name'             => 'Networking & Meetups',
						'slug'             => 'networking-and-meetups',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '125',
						'parent_id'        => null,
						'name'             => 'Sports & Outdoors',
						'slug'             => 'sports-and-outdoors',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '126',
						'parent_id'        => null,
						'name'             => 'Trade Shows & Conventions',
						'slug'             => 'trade-shows-conventions',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '127',
						'parent_id'        => null,
						'name'             => 'Training & Seminars',
						'slug'             => 'training-and-seminars',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '128',
						'parent_id'        => null,
						'name'             => 'Ceremonies',
						'slug'             => 'ceremonies',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '129',
						'parent_id'        => null,
						'name'             => 'Conferences',
						'slug'             => 'conferences',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '130',
						'parent_id'        => null,
						'name'             => 'Weddings',
						'slug'             => 'weddings',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '131',
						'parent_id'        => null,
						'name'             => 'Birthdays',
						'slug'             => 'birthdays',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '132',
						'parent_id'        => null,
						'name'             => 'Family Events',
						'slug'             => 'family-events',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '133',
						'parent_id'        => null,
						'name'             => 'Nightlife',
						'slug'             => 'nightlife',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
					[
						'translation_lang' => 'en',
						'translation_of'   => '134',
						'parent_id'        => null,
						'name'             => 'All others events',
						'slug'             => 'all-others-events',
						'description'      => null,
						'picture'          => 'app/default/categories/fa-folder-skin-blue.png',
						'icon_class'       => null,
						'lft'              => '0',
						'rgt'              => '0',
						'depth'            => '1',
						'type'             => 'classified',
						'is_for_permanent' => '0',
						'active'           => '1',
					],
				],
			],
		];
		
		foreach ($entries as $entry) {
			$subEntries = [];
			if (isset($entry['children'])) {
				$subEntries = $entry['children'];
				unset($entry['children']);
			}
			
			$lft = isset($rgt) ? ($rgt + 1) : 1;
			
			$entryId = DB::table('categories')->insertGetId($entry);
			DB::table('categories')->where('id', $entryId)->update([
				'translation_of' => $entryId,
				'lft'            => $lft,
			]);
			
			if (!empty($subEntries)) {
				foreach ($subEntries as $subEntry) {
					$lft = $lft + 1;
					$rgt = $lft + 1;
					
					$subEntryId = DB::table('categories')->insertGetId($subEntry);
					DB::table('categories')->where('id', $subEntryId)->update([
						'translation_of' => $subEntryId,
						'parent_id'      => $entryId,
						'lft'            => $lft,
						'rgt'            => $rgt,
					]);
				}
				$rgt = isset($rgt) ? ($rgt + 1) : 2;
			} else {
				$rgt = isset($lft) ? ($lft + 1) : 2;
			}
			
			DB::table('categories')->where('id', $entryId)->update([
				'rgt' => $rgt,
			]);
		}
	}
}
