<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FieldSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		$entries = [
			[
				'belongs_to'       => 'posts',
				'translation_lang' => 'en',
				'translation_of'   => '1',
				'name'             => 'Car Brand',
				'type'             => 'select',
				'max'              => null,
				'default'          => null,
				'required'         => '1',
				'use_as_filter'    => '1',
				'help'             => null,
				'active'           => '1',
				'options'          => [
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '1',
						'value'            => 'Toyota',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '2',
						'value'            => 'BMW',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '3',
						'value'            => 'Mercedes',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '4',
						'value'            => 'Chevrolet',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '5',
						'value'            => 'Cadillac',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '6',
						'value'            => 'Buick',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '7',
						'value'            => 'GMC',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '8',
						'value'            => 'Ford',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '9',
						'value'            => 'Chrysler',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '10',
						'value'            => 'Dodge',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '11',
						'value'            => 'Jeep',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '12',
						'value'            => 'Tesla',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '13',
						'value'            => 'Lexus',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '14',
						'value'            => 'Suzuki',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '15',
						'value'            => 'Mazda',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '16',
						'value'            => 'Honda',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '17',
						'value'            => 'Acura',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '18',
						'value'            => 'Mitsubishi',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '19',
						'value'            => 'Nissan',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '20',
						'value'            => 'Infiniti',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '21',
						'value'            => 'Audi',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '22',
						'value'            => 'Volkswagen',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '23',
						'value'            => 'Porsche',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '24',
						'value'            => 'Opel',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '25',
						'value'            => 'Jaguar',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '26',
						'value'            => 'Land Rover',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '27',
						'value'            => 'Mini',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '28',
						'value'            => 'Aston Martin',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '29',
						'value'            => 'Bentley',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '30',
						'value'            => 'Rolls Royce',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '31',
						'value'            => 'McLaren',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '32',
						'value'            => 'Fiat',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '33',
						'value'            => 'Alfa Romeo',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '34',
						'value'            => 'Maserati',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '35',
						'value'            => 'Ferrari',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '36',
						'value'            => 'Lamborghini',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '37',
						'value'            => 'Pagani',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '38',
						'value'            => 'Lancia',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '39',
						'value'            => 'Renault',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '40',
						'value'            => 'Peugeot',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '41',
						'value'            => 'Citroen',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '42',
						'value'            => 'Bugatti',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '43',
						'value'            => 'Tata',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '44',
						'value'            => 'Hyundai',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '45',
						'value'            => 'Kia',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '46',
						'value'            => 'Daewoo',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '47',
						'value'            => 'Volvo',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '48',
						'value'            => 'Saab',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '49',
						'value'            => 'Lada',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '50',
						'value'            => 'Volga',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '51',
						'value'            => 'Zil',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '52',
						'value'            => 'GAZ',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '53',
						'value'            => 'Geely',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '54',
						'value'            => 'Chery',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '55',
						'value'            => 'Hongqi',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '56',
						'value'            => 'Other',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
				],
			],
			[
				'belongs_to'       => 'posts',
				'translation_lang' => 'en',
				'translation_of'   => '2',
				'name'             => 'Car Model',
				'type'             => 'text',
				'max'              => null,
				'default'          => null,
				'required'         => '0',
				'use_as_filter'    => '0',
				'help'             => null,
				'active'           => '1',
			],
			[
				'belongs_to'       => 'posts',
				'translation_lang' => 'en',
				'translation_of'   => '3',
				'name'             => 'Year of registration',
				'type'             => 'number',
				'max'              => null,
				'default'          => null,
				'required'         => '0',
				'use_as_filter'    => '0',
				'help'             => null,
				'active'           => '1',
			],
			[
				'belongs_to'       => 'posts',
				'translation_lang' => 'en',
				'translation_of'   => '4',
				'name'             => 'Mileage',
				'type'             => 'text',
				'max'              => null,
				'default'          => null,
				'required'         => '0',
				'use_as_filter'    => '0',
				'help'             => null,
				'active'           => '1',
			],
			[
				'belongs_to'       => 'posts',
				'translation_lang' => 'en',
				'translation_of'   => '5',
				'name'             => 'Fuel Type',
				'type'             => 'select',
				'max'              => null,
				'default'          => null,
				'required'         => '0',
				'use_as_filter'    => '1',
				'help'             => null,
				'active'           => '1',
				'options'          => [
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '57',
						'value'            => 'Essence',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '58',
						'value'            => 'Diesel',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
				],
			],
			[
				'belongs_to'       => 'posts',
				'translation_lang' => 'en',
				'translation_of'   => '6',
				'name'             => 'Features',
				'type'             => 'checkbox_multiple',
				'max'              => null,
				'default'          => null,
				'required'         => '0',
				'use_as_filter'    => '1',
				'help'             => null,
				'active'           => '1',
				'options'          => [
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '59',
						'value'            => 'Air Conditioner',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '60',
						'value'            => 'GPS',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '61',
						'value'            => 'Security System',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '62',
						'value'            => 'Spare Tire',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
				],
			],
			[
				'belongs_to'       => 'posts',
				'translation_lang' => 'en',
				'translation_of'   => '7',
				'name'             => 'Transmission',
				'type'             => 'radio',
				'max'              => null,
				'default'          => null,
				'required'         => '0',
				'use_as_filter'    => '1',
				'help'             => null,
				'active'           => '1',
				'options'          => [
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '63',
						'value'            => 'Automatic',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '64',
						'value'            => 'Manual',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
				],
			],
			[
				'belongs_to'       => 'posts',
				'translation_lang' => 'en',
				'translation_of'   => '8',
				'name'             => 'Condition',
				'type'             => 'select',
				'max'              => null,
				'default'          => null,
				'required'         => '0',
				'use_as_filter'    => '1',
				'help'             => null,
				'active'           => '1',
				'options'          => [
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '65',
						'value'            => 'New',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '66',
						'value'            => 'Used',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
				],
			],
			[
				'belongs_to'       => 'posts',
				'translation_lang' => 'en',
				'translation_of'   => '9',
				'name'             => 'Size',
				'type'             => 'number',
				'max'              => '50',
				'default'          => null,
				'required'         => '1',
				'use_as_filter'    => '1',
				'help'             => null,
				'active'           => '1',
			],
			[
				'belongs_to'       => 'posts',
				'translation_lang' => 'en',
				'translation_of'   => '10',
				'name'             => 'Rooms',
				'type'             => 'select',
				'max'              => null,
				'default'          => null,
				'required'         => '1',
				'use_as_filter'    => '1',
				'help'             => null,
				'active'           => '1',
				'options'          => [
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '67',
						'value'            => '0',
						'parent_id'        => null,
						'lft'              => '2',
						'rgt'              => '3',
						'depth'            => '1',
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '68',
						'value'            => '1',
						'parent_id'        => null,
						'lft'              => '4',
						'rgt'              => '5',
						'depth'            => '1',
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '69',
						'value'            => '2',
						'parent_id'        => null,
						'lft'              => '6',
						'rgt'              => '7',
						'depth'            => '1',
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '70',
						'value'            => '3',
						'parent_id'        => null,
						'lft'              => '8',
						'rgt'              => '9',
						'depth'            => '1',
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '71',
						'value'            => '4',
						'parent_id'        => null,
						'lft'              => '10',
						'rgt'              => '11',
						'depth'            => '1',
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '72',
						'value'            => '5',
						'parent_id'        => null,
						'lft'              => '12',
						'rgt'              => '13',
						'depth'            => '1',
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '73',
						'value'            => '6',
						'parent_id'        => null,
						'lft'              => '14',
						'rgt'              => '15',
						'depth'            => '1',
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '74',
						'value'            => '7',
						'parent_id'        => null,
						'lft'              => '16',
						'rgt'              => '17',
						'depth'            => '1',
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '75',
						'value'            => '8',
						'parent_id'        => null,
						'lft'              => '18',
						'rgt'              => '19',
						'depth'            => '1',
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '76',
						'value'            => '9',
						'parent_id'        => null,
						'lft'              => '20',
						'rgt'              => '21',
						'depth'            => '1',
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '77',
						'value'            => '10',
						'parent_id'        => null,
						'lft'              => '22',
						'rgt'              => '23',
						'depth'            => '1',
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '78',
						'value'            => '> 10',
						'parent_id'        => null,
						'lft'              => '24',
						'rgt'              => '25',
						'depth'            => '1',
					],
				],
			],
			[
				'belongs_to'       => 'posts',
				'translation_lang' => 'en',
				'translation_of'   => '11',
				'name'             => 'Building Type',
				'type'             => 'select',
				'max'              => null,
				'default'          => null,
				'required'         => '0',
				'use_as_filter'    => '1',
				'help'             => null,
				'active'           => '1',
				'options'          => [
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '79',
						'value'            => 'Apartment',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '80',
						'value'            => 'House',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '81',
						'value'            => 'Office',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '82',
						'value'            => 'Store',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '83',
						'value'            => 'Plot of land',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
				],
			],
			[
				'belongs_to'       => 'posts',
				'translation_lang' => 'en',
				'translation_of'   => '12',
				'name'             => 'Parking',
				'type'             => 'checkbox',
				'max'              => null,
				'default'          => null,
				'required'         => '0',
				'use_as_filter'    => '1',
				'help'             => null,
				'active'           => '1',
			],
			[
				'belongs_to'       => 'posts',
				'translation_lang' => 'en',
				'translation_of'   => '13',
				'name'             => 'Furnished',
				'type'             => 'radio',
				'max'              => null,
				'default'          => null,
				'required'         => '0',
				'use_as_filter'    => '1',
				'help'             => null,
				'active'           => '1',
				'options'          => [
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '84',
						'value'            => 'Yes',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '85',
						'value'            => 'No',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
				],
			],
			[
				'belongs_to'       => 'posts',
				'translation_lang' => 'en',
				'translation_of'   => '14',
				'name'             => 'Mobile Brand',
				'type'             => 'select',
				'max'              => null,
				'default'          => null,
				'required'         => '0',
				'use_as_filter'    => '1',
				'help'             => null,
				'active'           => '1',
				'options'          => [
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '86',
						'value'            => 'Huawei',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '87',
						'value'            => 'Sony',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '88',
						'value'            => 'LG',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '89',
						'value'            => 'Samsung',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '90',
						'value'            => 'Nokia',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '91',
						'value'            => 'Alcatel-Lucent',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '92',
						'value'            => 'Siemens',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '93',
						'value'            => 'BlackBerry',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '94',
						'value'            => 'Apple',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '95',
						'value'            => 'Google',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '96',
						'value'            => 'Microsoft',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '97',
						'value'            => 'Motorola',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '98',
						'value'            => 'Other',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
				],
			],
			[
				'belongs_to'       => 'posts',
				'translation_lang' => 'en',
				'translation_of'   => '15',
				'name'             => 'Mobile Model',
				'type'             => 'text',
				'max'              => null,
				'default'          => null,
				'required'         => '0',
				'use_as_filter'    => '0',
				'help'             => null,
				'active'           => '1',
			],
			[
				'belongs_to'       => 'posts',
				'translation_lang' => 'en',
				'translation_of'   => '16',
				'name'             => 'Electronic Brand',
				'type'             => 'select',
				'max'              => null,
				'default'          => null,
				'required'         => '0',
				'use_as_filter'    => '1',
				'help'             => null,
				'active'           => '1',
				'options'          => [
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '99',
						'value'            => 'Huawei',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '100',
						'value'            => 'Lenovo',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '101',
						'value'            => 'TP-Link',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '102',
						'value'            => 'Xiaomi',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '103',
						'value'            => 'Canon',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '104',
						'value'            => 'Casio',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '105',
						'value'            => 'Epson',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '106',
						'value'            => 'Fuji',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '107',
						'value'            => 'Funai',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '108',
						'value'            => 'JVC',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '109',
						'value'            => 'Nikon',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '110',
						'value'            => 'Nintendo',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '111',
						'value'            => 'Olympus',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '112',
						'value'            => 'Panasonic',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '113',
						'value'            => 'Pentax',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '114',
						'value'            => 'Pioneer',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '115',
						'value'            => 'Sega',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '116',
						'value'            => 'Sharp',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '117',
						'value'            => 'Sony',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '118',
						'value'            => 'Toshiba',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '119',
						'value'            => 'Daewoo',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '120',
						'value'            => 'LG',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '121',
						'value'            => 'Samsung',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '122',
						'value'            => 'Acer',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '123',
						'value'            => 'Asus',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '124',
						'value'            => 'D-Link',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '125',
						'value'            => 'Gigabyte',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '126',
						'value'            => 'Beko',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '127',
						'value'            => 'Nokia',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '128',
						'value'            => 'Alcatel-Lucent',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '129',
						'value'            => 'Bosch',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '130',
						'value'            => 'Siemens',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '131',
						'value'            => 'Sennheiser',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '132',
						'value'            => 'Telefunken',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '133',
						'value'            => 'Philips',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '134',
						'value'            => 'Electrolux',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '135',
						'value'            => 'Russell Hobbs',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '136',
						'value'            => 'BlackBerry',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '137',
						'value'            => 'Thomson',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '138',
						'value'            => 'Amazon',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '139',
						'value'            => 'Apple',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '140',
						'value'            => 'Bose',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '141',
						'value'            => 'Cisco Systems',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '142',
						'value'            => 'Dell',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '143',
						'value'            => 'Gateway',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '144',
						'value'            => 'Google',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '145',
						'value'            => 'Hewlett-Packard',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '146',
						'value'            => 'IBM',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '147',
						'value'            => 'Intel',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '148',
						'value'            => 'Microsoft',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '149',
						'value'            => 'Motorola',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '150',
						'value'            => 'NVIDIA',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '151',
						'value'            => 'Packard Bell',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '152',
						'value'            => 'Qualcomm',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '153',
						'value'            => 'Seagate',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '154',
						'value'            => 'Sun Microsystems',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '155',
						'value'            => 'Vizio',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '156',
						'value'            => 'Western Digital',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '157',
						'value'            => 'Xerox',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '158',
						'value'            => 'Other',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
				],
			],
			[
				'belongs_to'       => 'posts',
				'translation_lang' => 'en',
				'translation_of'   => '17',
				'name'             => 'Model',
				'type'             => 'text',
				'max'              => null,
				'default'          => null,
				'required'         => '0',
				'use_as_filter'    => '0',
				'help'             => null,
				'active'           => '1',
			],
			[
				'belongs_to'       => 'posts',
				'translation_lang' => 'en',
				'translation_of'   => '18',
				'name'             => 'Start Date',
				'type'             => 'date',
				'max'              => '50',
				'default'          => null,
				'required'         => '0',
				'use_as_filter'    => '1',
				'help'             => null,
				'active'           => '1',
			],
			[
				'belongs_to'       => 'posts',
				'translation_lang' => 'en',
				'translation_of'   => '19',
				'name'             => 'Company',
				'type'             => 'text',
				'max'              => '100',
				'default'          => null,
				'required'         => '1',
				'use_as_filter'    => '0',
				'help'             => null,
				'active'           => '1',
			],
			[
				'belongs_to'       => 'posts',
				'translation_lang' => 'en',
				'translation_of'   => '20',
				'name'             => 'Work Type',
				'type'             => 'select',
				'max'              => null,
				'default'          => null,
				'required'         => '1',
				'use_as_filter'    => '1',
				'help'             => null,
				'active'           => '1',
				'options'          => [
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '159',
						'value'            => 'Full-time',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '160',
						'value'            => 'Part-time',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '161',
						'value'            => 'Temporary',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '162',
						'value'            => 'Internship',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
					[
						'field_id'         => null,
						'translation_lang' => 'en',
						'translation_of'   => '163',
						'value'            => 'Permanent',
						'parent_id'        => null,
						'lft'              => null,
						'rgt'              => null,
						'depth'            => null,
					],
				],
			],
			[
				'belongs_to'       => 'posts',
				'translation_lang' => 'en',
				'translation_of'   => '21',
				'name'             => 'Start date',
				'type'             => 'date',
				'max'              => '50',
				'default'          => null,
				'required'         => '1',
				'use_as_filter'    => '1',
				'help'             => null,
				'active'           => '1',
			],
			[
				'belongs_to'       => 'posts',
				'translation_lang' => 'en',
				'translation_of'   => '22',
				'name'             => 'End date',
				'type'             => 'date',
				'max'              => '50',
				'default'          => null,
				'required'         => '1',
				'use_as_filter'    => '1',
				'help'             => null,
				'active'           => '1',
			],
			[
				'belongs_to'       => 'posts',
				'translation_lang' => 'en',
				'translation_of'   => '23',
				'name'             => 'Event Address',
				'type'             => 'text',
				'max'              => '200',
				'default'          => null,
				'required'         => '1',
				'use_as_filter'    => '0',
				'help'             => null,
				'active'           => '1',
			],
			[
				'belongs_to'       => 'posts',
				'translation_lang' => 'en',
				'translation_of'   => '24',
				'name'             => 'Website',
				'type'             => 'url',
				'max'              => '100',
				'default'          => null,
				'required'         => '0',
				'use_as_filter'    => '0',
				'help'             => null,
				'active'           => '1',
			],
			[
				'belongs_to'       => 'posts',
				'translation_lang' => 'en',
				'translation_of'   => '25',
				'name'             => 'Video',
				'type'             => 'video',
				'max'              => '100',
				'default'          => null,
				'required'         => '0',
				'use_as_filter'    => '0',
				'help'             => null,
				'active'           => '1',
			],
			[
				'belongs_to'       => 'posts',
				'translation_lang' => 'en',
				'translation_of'   => '26',
				'name'             => 'Date Range',
				'type'             => 'date_range',
				'max'              => '100',
				'default'          => null,
				'required'         => '0',
				'use_as_filter'    => '1',
				'help'             => null,
				'active'           => '1',
			],
		];
		
		foreach ($entries as $entry) {
			$subEntries = [];
			if (isset($entry['options'])) {
				$subEntries = $entry['options'];
				unset($entry['options']);
			}
			
			$entryId = DB::table('fields')->insertGetId($entry);
			DB::table('fields')->where('id', $entryId)->update(['translation_of' => $entryId]);
			
			if (!empty($subEntries)) {
				
				$lft = isset($lft) ? $lft : 1;
				$rgt = isset($rgt) ? $rgt : 2;
				
				foreach ($subEntries as $subEntry) {
					$subEntryId = DB::table('fields_options')->insertGetId($subEntry);
					DB::table('fields_options')->where('id', $subEntryId)->update([
						'field_id'       => $entryId,
						'translation_of' => $subEntryId,
						'lft'            => $lft,
						'rgt'            => $rgt,
					]);
					
					$lft = $lft + 2;
					$rgt = $lft + 1;
				}
				
			}
		}
	}
}
